#!/bin/bash
#SBATCH -J funannotate
#SBATCH --account ACF-UTK0011
#SBATCH --mem=1200gb
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --time=24:00:00
#SBATCH --partition=campus-bigmem
#SBATCH --error=error/fun.e%j
#SBATCH --output=log/fun.o%j
#SBATCH --qos=campus-bigmem
#SBATCH --exclusive


cd /lustre/isaac/scratch/madler5/blue_pandora_seq/RNAseq_Processing/2_Trimmomatic/posttrim_paired/



singularity exec /lustre/isaac/scratch/jtorre28/singularity_containers/funannotate_v1.8.17.sif funannotate  train -i  /lustre/isaac/scratch/madler5/blue_pandora_seq/Genome_Assembly/hifiasm/hifiasm/pacbio-ont-sana-hic-1.hic.p_ctg.fa --left  raw-cat_1.fq --right raw-cat_2.fq --jaccard_clip  --no_trimmomatic --memory 1200G  --coverage 15 --species "pandora" --cpus 48 --aligners minimap2 -o /lustre/isaac/scratch/madler5/blue_pandora_seq/RNAseq_Processing/2_Trimmomatic/posttrim_paired/trainining.out
